image: node

stages:
    - lint
    - build

cache:
    paths:
        - node_modules/

linting:
    stage: lint
    script:
        - npm install eslint
        - node_modules/eslint/bin/eslint.js .

docker-build:
  stage: build
  image: docker:latest
  services:  # required by GitLab CI
    - docker:dind
  before_script:  # log into Docker hub
    - echo $DOCKER_TOKEN | docker login -u "$DOCKER_USER" --password-stdin
  script:
    - docker build -t flipstarter .
    - docker tag flipstarter flipstarter/flipstarter:latest
    - docker push flipstarter/flipstarter
  only:
    - master
